name: CD - Deploiement sur GitHub Pages
on:
  push:
    branches:["main"]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -name: Recuperation du code
      uses: actions/checkout@v3

      -name: Verification GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.16A2-1F0F}}
        publish_dir: .